### ISSUE TITLE
请问数据集是如何处理的呢

### ISSUE THREAD

**Issue by ARONZXA** [IRMVLab/DVLO#3]
校准文件缺少，只有一个单独的calib.txt

**Comment by liujiuming123** [comment]
Thanks! We have modified the file config.py now and you can check this time.

**Comment by liujiuming123** [comment]
It is directly downloaded from raw data in KITTI website, but with a conprehensive one.

**Comment by bkk12** [comment]
How to provide a separate calibration file for each frame or sensor in the dataset, rather than a comprehensive file

**Comment by TYBHC0052** [comment]
> > 校准文件缺少，只有一个单独的calib.txt
> 
> 我有同样的问题！当我运行 train.py 时，系统无法对每帧的calib.txt进行微调，因为：FileNotFoundError：[Errno 2] 没有这样的文件或目录：'./data_odometry_color/dataset/sequences/07/calib/000000.txt' 是否有任何额外的过程可以将单个calib.txt转换为每一帧？

May I ask if this issue has been resolved? I want to ask for advice.

**Comment by hhxin2001** [comment]
> It is directly downloaded from raw data in KITTI website, but with a conprehensive one.
In addition to the problem with the dataset, I run this code now, and there is also a problem with dimension inconsistencies in the network part, what is the reason for this?
Traceback (most recent call last):
  File "train.py", line 341, in <module>
    main()
  File "train.py", line 134, in main
    eval_pose(model, test_dir_list, init_epoch)
  File "train.py", line 276, in eval_pose
    model(pos2, pos1, imback2, imback1, xy2, xy1, T_gt, T_trans, T_trans_inv, pts_valid2, pts_valid1)
  File "/home/sdb/hehaixin/.conda/envs/dvlo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sdb/hehaixin/.conda/envs/dvlo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sdb/hehaixin/DVLO/pwclonet_model.py", line 332, in forward
    l0_xy_cor_f1[batch, :l0_batch_xy_f1.shape[0], :] = l0_batch_xy_f1  # [B, N, 2] 当前批次有效点的二维坐标
RuntimeError: The expanded size of the tensor (700) must match the existing size (1381) at non-singleton dimension 0.  Target sizes: [700, 2].  Tensor sizes: [1381, 2]

**Comment by rich2300** [comment]
请问这个问题解决了吗？我也遇到了这个问题

**Comment by diuzhevVlad** [comment]
@liujiuming123 Hi, thank you! Do you have any updates on this issue?

**Comment by Lyoid** [comment]
求求更新一下这个祖传的readme吧

**Comment by Tian0822** [comment]
> > > 校准文件缺少，只有一个单独的calib.txt
> > 
> > 
> > 我有同样的问题！当我运行 train.py 时，系统无法对每帧的calib.txt进行微调，因为：FileNotFoundError：[Errno 2] 没有这样的文件或目录：'./data_odometry_color/dataset/sequences/07/calib/000000.txt' 是否有任何额外的过程可以将单个calib.txt转换为每一帧？
> 
> May I ask if this issue has been resolved? I want to ask for advice.

@TYBHC0052 Hello, has this problem been solved? I also encountered this problem.
