### ISSUE TITLE
No module named 'cross_swin_transformer'

### ISSUE THREAD

**Issue by TYBHC0052** [IRMVLab/DVLO#5]
"Hello! Why do I get a ModuleNotFoundError: No module named 'cross_swin_transformer' when I run python train.py?"
The specific error is as follows.

`Traceback (most recent call last):
  File "train.py", line 20, in <module>
    from pwclonet_model import pwc_model, get_loss
  File "/home/selfdriving/yinqian/DVLO/pwclonet_model.py", line 18, in <module>
    from cross_swin_transformer import Cross_BasicLayer
ModuleNotFoundError: No module named 'cross_swin_transformer'`

**Comment by TheGreyMarble** [comment]
I also find that issue, I just delete it ,but don’t know what    Will happen
